language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: server-user-tfm
  api_key:
    secure: "dADm0nJMyWogWeTeaRr+jbQQ0jsCy7K4xf/1A2+9HcRF/ZQAk1egXuE4yWZWiAX4K5hY5/SzlxY3qUhD3BCfhDzFaQfQIK0BOEyUfe+yddZUzCK1Gn/HYYUhrmPCOjS1D5L+OHXhJmkb+4uNqgFFI4J2Or2glmnF0N3BmgBtccbyzGtKVYKjvOEOxEJDTnr5Mzso4gnOhu8nHxLiwyhGjyZhE3SjCcWKda6a5MdGY8l4PashE1mBfISeVmvjyGdmhUBTvJtdc5f0S6UyNmiAIlbP/Q0q+X4+Q1fyoLY2m17IrOcD9P543WafItc7RDHgeFPNjUhKyjMjHV3Ccd05qQA53VHhNztwnhqnNTfnvlhwaJpwKpFdBOlCNlNPLtO2jvbmKA7PZ3vsqzjl71BaBV1vzQ0Pa6O6TSGEjmi+miD43Jy2E23Qs+gm/10ODCLMyZ4zgzAqg/53ile98PQMPUqy3ZK0hDK28hiDNvrRKM+j43RKl4ER2x4j7VAx8ybQ63Lns9Jm/ZtkN2oqJj9IukknkEjpbjERShPvfWHRC/UeuOY4v9D8f56qi6V+D5eVkDR4mCrAIOby16dfEOvjoAv/9r72dcP29Hi7Kexw24rQFh6t5Itn8UDA41q0yQbjubIOgcQ8UIosundoK00c2G11IKvwQSRxbaeb5fceh8o="