language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: server-user-tfm
  api_key:
    secure: SbpvT1NVD0PtTXPtvuVysdITZAad0jQRiChNzH0G179BJwHt+vQ1DK9pyQH/UFD7kypjwdxPx/k6af/9PV+8CtmqAxpqDgAZZz/apmqPa/1/nEeHfxHbK2HZa82INuvDLmEDWGT4Pku5n2rDfmWdc8NmseojRrAzFdPNklhxHNDaxDVgJctH4bOVU2g2hLuG43tIsViBROLY0FWyAER0zOa5kl3XLTtfmpVRMBCY2anoRzRXh49Y3Q6fcxLe4hxbulC+1CXg9dfRFRuhqGbsyWR/i8xbo2Q6KKFz84oA1lXT7OiKIJfM/OkOhROn76jm7MsToPdhQDqnb1ZrG2JzSf8q04Wof/K6vUMfkeUuuzxtAy+UEmpDIh5Pq7SE69JecM8nCx5ajOZmeBr5CgfY8heS8xBmDDEnTej0MLnl0HBg3MIwddei8EVCBfClnYt9sdY5+3ht1W6OI53KFxjT8b1nwS1cjNaBrCKFYmJgWmnc5aPdIMuQgu+pcw2hfcyRCQMkcAYNvdArztZFlLowIPKSWHfZrbZESg5j9iT8jVi3wBaIKtR4Pr9RfmcthboI6t43hwSnmv8ohvihBXcLtOogYD+hSkZu2M2538rqP8TO+HYC6wzoD3TDVi1viyNkayq/wp2+CnHcdSXTEJBc/53GcZiTDDVEkto1lDWJ8vs=
